import Sidebar from "@/components/Sidebar";
import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="flex h-screen bg-slate-900 text-gray-100 overflow-hidden">
          {/* BG */}
          <div className="fixed inset-0 z-0">
            <div className="absolute inset-0 bg-slate-900 opacity-80" />
            <div className="absolute inset-0 backdrop-blur-sm" />
          </div>
          <Sidebar />
          {children}
        </div>
      </body>
    </html>
  );
}
